services:
  personal-site:
    build: .
    ports:
      - "4321:4321"

  playwright:
    build:
      context: .
      dockerfile: dockerfile.playwright
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
    volumes:
      - ./public:/app/public
