import { expect, test } from "@playwright/test";
import { existsSync, readdirSync, statSync } from "node:fs";
import path from "node:path";

// PDFs are generated by the pdf-export Astro integration during `pnpm build`.
// These checks verify the build pipeline produced every expected download.

function expectedPdfNames() {
  const distPath = path.resolve("dist");

  if (!existsSync(distPath)) {
    throw new Error("Build output was not found. Run `pnpm build` first.");
  }

  const slugsIn = (subdir: string) =>
    readdirSync(path.join(distPath, subdir), { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .sort();

  return [
    "hans-askov-cv.pdf",
    ...slugsIn("cv").map((slug) => `hans-askov-cv-${slug}.pdf`),
    ...slugsIn("application-letter").map((slug) => `application-letter-${slug}.pdf`),
  ];
}

test("build generated every CV and application letter PDF", async () => {
  const pdfNames = expectedPdfNames();

  expect(pdfNames.length).toBeGreaterThan(1);

  for (const name of pdfNames) {
    const pdfPath = path.resolve("dist", name);
    expect(existsSync(pdfPath), `${name} is missing from dist/`).toBe(true);
    expect(statSync(pdfPath).size, `${name} is suspiciously small`).toBeGreaterThan(10_000);
  }
});
